using NUnit.Framework;
using WodiLib.Event.EventCommand;

namespace WodiLib.Test.Event.EventCommand
{
    [TestFixture]
    public class MapChipSettingsTest
    {
        private static readonly object[] TestCaseSource =
        {
            new object[] { new[] { false, false, false, false, false, false, false, false }, 0 },
            new object[] { new[] { true, false, false, false, false, false, false, false }, 1 },
            new object[] { new[] { false, true, false, false, false, false, false, false }, 2 },
            new object[] { new[] { true, true, false, false, false, false, false, false }, 3 },
            new object[] { new[] { false, false, true, false, false, false, false, false }, 4 },
            new object[] { new[] { true, false, true, false, false, false, false, false }, 5 },
            new object[] { new[] { false, true, true, false, false, false, false, false }, 6 },
            new object[] { new[] { true, true, true, false, false, false, false, false }, 7 },
            new object[] { new[] { false, false, false, true, false, false, false, false }, 8 },
            new object[] { new[] { true, false, false, true, false, false, false, false }, 9 },
            new object[] { new[] { false, true, false, true, false, false, false, false }, 10 },
            new object[] { new[] { true, true, false, true, false, false, false, false }, 11 },
            new object[] { new[] { false, false, true, true, false, false, false, false }, 12 },
            new object[] { new[] { true, false, true, true, false, false, false, false }, 13 },
            new object[] { new[] { false, true, true, true, false, false, false, false }, 14 },
            new object[] { new[] { true, true, true, true, false, false, false, false }, 15 },
            new object[] { new[] { false, false, false, false, true, false, false, false }, 16 },
            new object[] { new[] { true, false, false, false, true, false, false, false }, 17 },
            new object[] { new[] { false, true, false, false, true, false, false, false }, 18 },
            new object[] { new[] { true, true, false, false, true, false, false, false }, 19 },
            new object[] { new[] { false, false, true, false, true, false, false, false }, 20 },
            new object[] { new[] { true, false, true, false, true, false, false, false }, 21 },
            new object[] { new[] { false, true, true, false, true, false, false, false }, 22 },
            new object[] { new[] { true, true, true, false, true, false, false, false }, 23 },
            new object[] { new[] { false, false, false, true, true, false, false, false }, 24 },
            new object[] { new[] { true, false, false, true, true, false, false, false }, 25 },
            new object[] { new[] { false, true, false, true, true, false, false, false }, 26 },
            new object[] { new[] { true, true, false, true, true, false, false, false }, 27 },
            new object[] { new[] { false, false, true, true, true, false, false, false }, 28 },
            new object[] { new[] { true, false, true, true, true, false, false, false }, 29 },
            new object[] { new[] { false, true, true, true, true, false, false, false }, 30 },
            new object[] { new[] { true, true, true, true, true, false, false, false }, 31 },
            new object[] { new[] { false, false, false, false, false, true, false, false }, 64 },
            new object[] { new[] { true, false, false, false, false, true, false, false }, 65 },
            new object[] { new[] { false, true, false, false, false, true, false, false }, 66 },
            new object[] { new[] { true, true, false, false, false, true, false, false }, 67 },
            new object[] { new[] { false, false, true, false, false, true, false, false }, 68 },
            new object[] { new[] { true, false, true, false, false, true, false, false }, 69 },
            new object[] { new[] { false, true, true, false, false, true, false, false }, 70 },
            new object[] { new[] { true, true, true, false, false, true, false, false }, 71 },
            new object[] { new[] { false, false, false, true, false, true, false, false }, 72 },
            new object[] { new[] { true, false, false, true, false, true, false, false }, 73 },
            new object[] { new[] { false, true, false, true, false, true, false, false }, 74 },
            new object[] { new[] { true, true, false, true, false, true, false, false }, 75 },
            new object[] { new[] { false, false, true, true, false, true, false, false }, 76 },
            new object[] { new[] { true, false, true, true, false, true, false, false }, 77 },
            new object[] { new[] { false, true, true, true, false, true, false, false }, 78 },
            new object[] { new[] { true, true, true, true, false, true, false, false }, 79 },
            new object[] { new[] { false, false, false, false, true, true, false, false }, 80 },
            new object[] { new[] { true, false, false, false, true, true, false, false }, 81 },
            new object[] { new[] { false, true, false, false, true, true, false, false }, 82 },
            new object[] { new[] { true, true, false, false, true, true, false, false }, 83 },
            new object[] { new[] { false, false, true, false, true, true, false, false }, 84 },
            new object[] { new[] { true, false, true, false, true, true, false, false }, 85 },
            new object[] { new[] { false, true, true, false, true, true, false, false }, 86 },
            new object[] { new[] { true, true, true, false, true, true, false, false }, 87 },
            new object[] { new[] { false, false, false, true, true, true, false, false }, 88 },
            new object[] { new[] { true, false, false, true, true, true, false, false }, 89 },
            new object[] { new[] { false, true, false, true, true, true, false, false }, 90 },
            new object[] { new[] { true, true, false, true, true, true, false, false }, 91 },
            new object[] { new[] { false, false, true, true, true, true, false, false }, 92 },
            new object[] { new[] { true, false, true, true, true, true, false, false }, 93 },
            new object[] { new[] { false, true, true, true, true, true, false, false }, 94 },
            new object[] { new[] { true, true, true, true, true, true, false, false }, 95 },
            new object[] { new[] { false, false, false, false, false, false, true, false }, 512 },
            new object[] { new[] { true, false, false, false, false, false, true, false }, 513 },
            new object[] { new[] { false, true, false, false, false, false, true, false }, 514 },
            new object[] { new[] { true, true, false, false, false, false, true, false }, 515 },
            new object[] { new[] { false, false, true, false, false, false, true, false }, 516 },
            new object[] { new[] { true, false, true, false, false, false, true, false }, 517 },
            new object[] { new[] { false, true, true, false, false, false, true, false }, 518 },
            new object[] { new[] { true, true, true, false, false, false, true, false }, 519 },
            new object[] { new[] { false, false, false, true, false, false, true, false }, 520 },
            new object[] { new[] { true, false, false, true, false, false, true, false }, 521 },
            new object[] { new[] { false, true, false, true, false, false, true, false }, 522 },
            new object[] { new[] { true, true, false, true, false, false, true, false }, 523 },
            new object[] { new[] { false, false, true, true, false, false, true, false }, 524 },
            new object[] { new[] { true, false, true, true, false, false, true, false }, 525 },
            new object[] { new[] { false, true, true, true, false, false, true, false }, 526 },
            new object[] { new[] { true, true, true, true, false, false, true, false }, 527 },
            new object[] { new[] { false, false, false, false, true, false, true, false }, 528 },
            new object[] { new[] { true, false, false, false, true, false, true, false }, 529 },
            new object[] { new[] { false, true, false, false, true, false, true, false }, 530 },
            new object[] { new[] { true, true, false, false, true, false, true, false }, 531 },
            new object[] { new[] { false, false, true, false, true, false, true, false }, 532 },
            new object[] { new[] { true, false, true, false, true, false, true, false }, 533 },
            new object[] { new[] { false, true, true, false, true, false, true, false }, 534 },
            new object[] { new[] { true, true, true, false, true, false, true, false }, 535 },
            new object[] { new[] { false, false, false, true, true, false, true, false }, 536 },
            new object[] { new[] { true, false, false, true, true, false, true, false }, 537 },
            new object[] { new[] { false, true, false, true, true, false, true, false }, 538 },
            new object[] { new[] { true, true, false, true, true, false, true, false }, 539 },
            new object[] { new[] { false, false, true, true, true, false, true, false }, 540 },
            new object[] { new[] { true, false, true, true, true, false, true, false }, 541 },
            new object[] { new[] { false, true, true, true, true, false, true, false }, 542 },
            new object[] { new[] { true, true, true, true, true, false, true, false }, 543 },
            new object[] { new[] { false, false, false, false, false, true, true, false }, 576 },
            new object[] { new[] { true, false, false, false, false, true, true, false }, 577 },
            new object[] { new[] { false, true, false, false, false, true, true, false }, 578 },
            new object[] { new[] { true, true, false, false, false, true, true, false }, 579 },
            new object[] { new[] { false, false, true, false, false, true, true, false }, 580 },
            new object[] { new[] { true, false, true, false, false, true, true, false }, 581 },
            new object[] { new[] { false, true, true, false, false, true, true, false }, 582 },
            new object[] { new[] { true, true, true, false, false, true, true, false }, 583 },
            new object[] { new[] { false, false, false, true, false, true, true, false }, 584 },
            new object[] { new[] { true, false, false, true, false, true, true, false }, 585 },
            new object[] { new[] { false, true, false, true, false, true, true, false }, 586 },
            new object[] { new[] { true, true, false, true, false, true, true, false }, 587 },
            new object[] { new[] { false, false, true, true, false, true, true, false }, 588 },
            new object[] { new[] { true, false, true, true, false, true, true, false }, 589 },
            new object[] { new[] { false, true, true, true, false, true, true, false }, 590 },
            new object[] { new[] { true, true, true, true, false, true, true, false }, 591 },
            new object[] { new[] { false, false, false, false, true, true, true, false }, 592 },
            new object[] { new[] { true, false, false, false, true, true, true, false }, 593 },
            new object[] { new[] { false, true, false, false, true, true, true, false }, 594 },
            new object[] { new[] { true, true, false, false, true, true, true, false }, 595 },
            new object[] { new[] { false, false, true, false, true, true, true, false }, 596 },
            new object[] { new[] { true, false, true, false, true, true, true, false }, 597 },
            new object[] { new[] { false, true, true, false, true, true, true, false }, 598 },
            new object[] { new[] { true, true, true, false, true, true, true, false }, 599 },
            new object[] { new[] { false, false, false, true, true, true, true, false }, 600 },
            new object[] { new[] { true, false, false, true, true, true, true, false }, 601 },
            new object[] { new[] { false, true, false, true, true, true, true, false }, 602 },
            new object[] { new[] { true, true, false, true, true, true, true, false }, 603 },
            new object[] { new[] { false, false, true, true, true, true, true, false }, 604 },
            new object[] { new[] { true, false, true, true, true, true, true, false }, 605 },
            new object[] { new[] { false, true, true, true, true, true, true, false }, 606 },
            new object[] { new[] { true, true, true, true, true, true, true, false }, 607 },
            new object[] { new[] { false, false, false, false, false, false, false, true }, 128 },
            new object[] { new[] { true, false, false, false, false, false, false, true }, 129 },
            new object[] { new[] { false, true, false, false, false, false, false, true }, 130 },
            new object[] { new[] { true, true, false, false, false, false, false, true }, 131 },
            new object[] { new[] { false, false, true, false, false, false, false, true }, 132 },
            new object[] { new[] { true, false, true, false, false, false, false, true }, 133 },
            new object[] { new[] { false, true, true, false, false, false, false, true }, 134 },
            new object[] { new[] { true, true, true, false, false, false, false, true }, 135 },
            new object[] { new[] { false, false, false, true, false, false, false, true }, 136 },
            new object[] { new[] { true, false, false, true, false, false, false, true }, 137 },
            new object[] { new[] { false, true, false, true, false, false, false, true }, 138 },
            new object[] { new[] { true, true, false, true, false, false, false, true }, 139 },
            new object[] { new[] { false, false, true, true, false, false, false, true }, 140 },
            new object[] { new[] { true, false, true, true, false, false, false, true }, 141 },
            new object[] { new[] { false, true, true, true, false, false, false, true }, 142 },
            new object[] { new[] { true, true, true, true, false, false, false, true }, 143 },
            new object[] { new[] { false, false, false, false, true, false, false, true }, 144 },
            new object[] { new[] { true, false, false, false, true, false, false, true }, 145 },
            new object[] { new[] { false, true, false, false, true, false, false, true }, 146 },
            new object[] { new[] { true, true, false, false, true, false, false, true }, 147 },
            new object[] { new[] { false, false, true, false, true, false, false, true }, 148 },
            new object[] { new[] { true, false, true, false, true, false, false, true }, 149 },
            new object[] { new[] { false, true, true, false, true, false, false, true }, 150 },
            new object[] { new[] { true, true, true, false, true, false, false, true }, 151 },
            new object[] { new[] { false, false, false, true, true, false, false, true }, 152 },
            new object[] { new[] { true, false, false, true, true, false, false, true }, 153 },
            new object[] { new[] { false, true, false, true, true, false, false, true }, 154 },
            new object[] { new[] { true, true, false, true, true, false, false, true }, 155 },
            new object[] { new[] { false, false, true, true, true, false, false, true }, 156 },
            new object[] { new[] { true, false, true, true, true, false, false, true }, 157 },
            new object[] { new[] { false, true, true, true, true, false, false, true }, 158 },
            new object[] { new[] { true, true, true, true, true, false, false, true }, 159 },
            new object[] { new[] { false, false, false, false, false, true, false, true }, 192 },
            new object[] { new[] { true, false, false, false, false, true, false, true }, 193 },
            new object[] { new[] { false, true, false, false, false, true, false, true }, 194 },
            new object[] { new[] { true, true, false, false, false, true, false, true }, 195 },
            new object[] { new[] { false, false, true, false, false, true, false, true }, 196 },
            new object[] { new[] { true, false, true, false, false, true, false, true }, 197 },
            new object[] { new[] { false, true, true, false, false, true, false, true }, 198 },
            new object[] { new[] { true, true, true, false, false, true, false, true }, 199 },
            new object[] { new[] { false, false, false, true, false, true, false, true }, 200 },
            new object[] { new[] { true, false, false, true, false, true, false, true }, 201 },
            new object[] { new[] { false, true, false, true, false, true, false, true }, 202 },
            new object[] { new[] { true, true, false, true, false, true, false, true }, 203 },
            new object[] { new[] { false, false, true, true, false, true, false, true }, 204 },
            new object[] { new[] { true, false, true, true, false, true, false, true }, 205 },
            new object[] { new[] { false, true, true, true, false, true, false, true }, 206 },
            new object[] { new[] { true, true, true, true, false, true, false, true }, 207 },
            new object[] { new[] { false, false, false, false, true, true, false, true }, 208 },
            new object[] { new[] { true, false, false, false, true, true, false, true }, 209 },
            new object[] { new[] { false, true, false, false, true, true, false, true }, 210 },
            new object[] { new[] { true, true, false, false, true, true, false, true }, 211 },
            new object[] { new[] { false, false, true, false, true, true, false, true }, 212 },
            new object[] { new[] { true, false, true, false, true, true, false, true }, 213 },
            new object[] { new[] { false, true, true, false, true, true, false, true }, 214 },
            new object[] { new[] { true, true, true, false, true, true, false, true }, 215 },
            new object[] { new[] { false, false, false, true, true, true, false, true }, 216 },
            new object[] { new[] { true, false, false, true, true, true, false, true }, 217 },
            new object[] { new[] { false, true, false, true, true, true, false, true }, 218 },
            new object[] { new[] { true, true, false, true, true, true, false, true }, 219 },
            new object[] { new[] { false, false, true, true, true, true, false, true }, 220 },
            new object[] { new[] { true, false, true, true, true, true, false, true }, 221 },
            new object[] { new[] { false, true, true, true, true, true, false, true }, 222 },
            new object[] { new[] { true, true, true, true, true, true, false, true }, 223 },
            new object[] { new[] { false, false, false, false, false, false, true, true }, 640 },
            new object[] { new[] { true, false, false, false, false, false, true, true }, 641 },
            new object[] { new[] { false, true, false, false, false, false, true, true }, 642 },
            new object[] { new[] { true, true, false, false, false, false, true, true }, 643 },
            new object[] { new[] { false, false, true, false, false, false, true, true }, 644 },
            new object[] { new[] { true, false, true, false, false, false, true, true }, 645 },
            new object[] { new[] { false, true, true, false, false, false, true, true }, 646 },
            new object[] { new[] { true, true, true, false, false, false, true, true }, 647 },
            new object[] { new[] { false, false, false, true, false, false, true, true }, 648 },
            new object[] { new[] { true, false, false, true, false, false, true, true }, 649 },
            new object[] { new[] { false, true, false, true, false, false, true, true }, 650 },
            new object[] { new[] { true, true, false, true, false, false, true, true }, 651 },
            new object[] { new[] { false, false, true, true, false, false, true, true }, 652 },
            new object[] { new[] { true, false, true, true, false, false, true, true }, 653 },
            new object[] { new[] { false, true, true, true, false, false, true, true }, 654 },
            new object[] { new[] { true, true, true, true, false, false, true, true }, 655 },
            new object[] { new[] { false, false, false, false, true, false, true, true }, 656 },
            new object[] { new[] { true, false, false, false, true, false, true, true }, 657 },
            new object[] { new[] { false, true, false, false, true, false, true, true }, 658 },
            new object[] { new[] { true, true, false, false, true, false, true, true }, 659 },
            new object[] { new[] { false, false, true, false, true, false, true, true }, 660 },
            new object[] { new[] { true, false, true, false, true, false, true, true }, 661 },
            new object[] { new[] { false, true, true, false, true, false, true, true }, 662 },
            new object[] { new[] { true, true, true, false, true, false, true, true }, 663 },
            new object[] { new[] { false, false, false, true, true, false, true, true }, 664 },
            new object[] { new[] { true, false, false, true, true, false, true, true }, 665 },
            new object[] { new[] { false, true, false, true, true, false, true, true }, 666 },
            new object[] { new[] { true, true, false, true, true, false, true, true }, 667 },
            new object[] { new[] { false, false, true, true, true, false, true, true }, 668 },
            new object[] { new[] { true, false, true, true, true, false, true, true }, 669 },
            new object[] { new[] { false, true, true, true, true, false, true, true }, 670 },
            new object[] { new[] { true, true, true, true, true, false, true, true }, 671 },
            new object[] { new[] { false, false, false, false, false, true, true, true }, 704 },
            new object[] { new[] { true, false, false, false, false, true, true, true }, 705 },
            new object[] { new[] { false, true, false, false, false, true, true, true }, 706 },
            new object[] { new[] { true, true, false, false, false, true, true, true }, 707 },
            new object[] { new[] { false, false, true, false, false, true, true, true }, 708 },
            new object[] { new[] { true, false, true, false, false, true, true, true }, 709 },
            new object[] { new[] { false, true, true, false, false, true, true, true }, 710 },
            new object[] { new[] { true, true, true, false, false, true, true, true }, 711 },
            new object[] { new[] { false, false, false, true, false, true, true, true }, 712 },
            new object[] { new[] { true, false, false, true, false, true, true, true }, 713 },
            new object[] { new[] { false, true, false, true, false, true, true, true }, 714 },
            new object[] { new[] { true, true, false, true, false, true, true, true }, 715 },
            new object[] { new[] { false, false, true, true, false, true, true, true }, 716 },
            new object[] { new[] { true, false, true, true, false, true, true, true }, 717 },
            new object[] { new[] { false, true, true, true, false, true, true, true }, 718 },
            new object[] { new[] { true, true, true, true, false, true, true, true }, 719 },
            new object[] { new[] { false, false, false, false, true, true, true, true }, 720 },
            new object[] { new[] { true, false, false, false, true, true, true, true }, 721 },
            new object[] { new[] { false, true, false, false, true, true, true, true }, 722 },
            new object[] { new[] { true, true, false, false, true, true, true, true }, 723 },
            new object[] { new[] { false, false, true, false, true, true, true, true }, 724 },
            new object[] { new[] { true, false, true, false, true, true, true, true }, 725 },
            new object[] { new[] { false, true, true, false, true, true, true, true }, 726 },
            new object[] { new[] { true, true, true, false, true, true, true, true }, 727 },
            new object[] { new[] { false, false, false, true, true, true, true, true }, 728 },
            new object[] { new[] { true, false, false, true, true, true, true, true }, 729 },
            new object[] { new[] { false, true, false, true, true, true, true, true }, 730 },
            new object[] { new[] { true, true, false, true, true, true, true, true }, 731 },
            new object[] { new[] { false, false, true, true, true, true, true, true }, 732 },
            new object[] { new[] { true, false, true, true, true, true, true, true }, 733 },
            new object[] { new[] { false, true, true, true, true, true, true, true }, 734 },
            new object[] { new[] { true, true, true, true, true, true, true, true }, 735 }
        };

        [TestCaseSource(nameof(TestCaseSource))]
        public static void CreateTest(bool[] flags, int flagValue)
        {
            var instance = new MapChipSettings(flagValue);

            Assert.AreEqual(instance.IsNoDown, flags[0]);
            Assert.AreEqual(instance.IsNoLeft, flags[1]);
            Assert.AreEqual(instance.IsNoRight, flags[2]);
            Assert.AreEqual(instance.IsNoUp, flags[3]);
            Assert.AreEqual(instance.IsAboveHero, flags[4]);
            Assert.AreEqual(instance.IsHalfTrans, flags[5]);
            Assert.AreEqual(instance.IsMatchLowerLayer, flags[6]);
            Assert.AreEqual(instance.IsCounter, flags[7]);
        }

        [TestCaseSource(nameof(TestCaseSource))]
        public static void ToIntTest(bool[] flags, int flagValue)
        {
            var instance = new MapChipSettings
            {
                IsNoDown = flags[0],
                IsNoLeft = flags[1],
                IsNoRight = flags[2],
                IsNoUp = flags[3],
                IsAboveHero = flags[4],
                IsHalfTrans = flags[5],
                IsMatchLowerLayer = flags[6],
                IsCounter = flags[7]
            };
            Assert.AreEqual(instance.ToInt(), flagValue);
        }
    }
}
