//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WodiLibSample.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Form1Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form1Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WodiLibSample.Resources.Form1Resource", typeof(Form1Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitle_Error {
            get {
                return ResourceManager.GetString("DialogTitle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクトが正しく読み込まれませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorProjectLoad {
            get {
                return ResourceManager.GetString("ErrorProjectLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コモンイベント {0} のイベントコマンドコードをロード中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingCommonEventCode {
            get {
                return ResourceManager.GetString("LoadingCommonEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コモンイベント {0} のイベントコマンド文をロード中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingCommonEventCommandSentence {
            get {
                return ResourceManager.GetString("LoadingCommonEventCommandSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コモンイベント一覧をロード中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingCommonEventList {
            get {
                return ResourceManager.GetString("LoadingCommonEventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マップイベントをロード中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingMapEvent {
            get {
                return ResourceManager.GetString("LoadingMapEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マップイベント {0} のイベントコマンドコードをロード中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingMapEventCode {
            get {
                return ResourceManager.GetString("LoadingMapEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マップイベント {0} のイベントコマンド文をロード中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingMapEventCommandSentence {
            get {
                return ResourceManager.GetString("LoadingMapEventCommandSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マップイベント一覧をロード中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingMapEventList {
            get {
                return ResourceManager.GetString("LoadingMapEventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マップデータをロード中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingMapFile {
            get {
                return ResourceManager.GetString("LoadingMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マップ一覧をロード中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingMapList {
            get {
                return ResourceManager.GetString("LoadingMapList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクトをロード中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectLoading {
            get {
                return ResourceManager.GetString("ProjectLoading", resourceCulture);
            }
        }
    }
}
